import { describe, expect, it } from 'vitest'
import type { BrowserCommand } from '../browser/protocol.ts'
import { browserIntent, SITES } from './browserIntent.ts'

const ROWS: Array<[string, BrowserCommand]> = [
  // New tab
  ['ava uus vaheleht', { kind: 'newTab' }],
  ['Uus vaheleht.', { kind: 'newTab' }],
  ['ava vaheleht', { kind: 'newTab' }],
  ['new tab', { kind: 'newTab' }],
  ['Open a new tab.', { kind: 'newTab' }],
  // Close
  ['sulge vaheleht', { kind: 'closeTab' }],
  ['Sulge see vaheleht.', { kind: 'closeTab' }],
  ['pane vaheleht kinni', { kind: 'closeTab' }],
  ['close tab', { kind: 'closeTab' }],
  ['close this tab', { kind: 'closeTab' }],
  // Next and previous
  ['järgmine vaheleht', { kind: 'switchTab', to: 'next' }],
  ['eelmine vaheleht', { kind: 'switchTab', to: 'previous' }],
  ['next tab', { kind: 'switchTab', to: 'next' }],
  ['previous tab', { kind: 'switchTab', to: 'previous' }],
  // By number
  ['kolmas vaheleht', { kind: 'switchTab', to: { index: 3 } }],
  ['vaheleht kolm', { kind: 'switchTab', to: { index: 3 } }],
  ['vaheleht number 3', { kind: 'switchTab', to: { index: 3 } }],
  ['mine kolmandale vahelehele', { kind: 'switchTab', to: { index: 3 } }],
  ['esimene vaheleht', { kind: 'switchTab', to: { index: 1 } }],
  ['tab three', { kind: 'switchTab', to: { index: 3 } }],
  ['third tab', { kind: 'switchTab', to: { index: 3 } }],
  ['go to tab 3', { kind: 'switchTab', to: { index: 3 } }],
  // Sites by name
  ['Ava WhatsApp.', { kind: 'goTo', url: 'https://web.whatsapp.com/' }],
  ['ava vatsap', { kind: 'goTo', url: 'https://web.whatsapp.com/' }],
  ['ava messenger', { kind: 'goTo', url: SITES.messenger }],
  ['Ava Messenger.', { kind: 'goTo', url: 'https://www.messenger.com/' }],
  ['ava gmail', { kind: 'goTo', url: 'https://mail.google.com/' }],
  ['mine lehele postimees.ee', { kind: 'goTo', url: 'https://postimees.ee' }],
  ['mine lehele postimees', { kind: 'goTo', url: 'https://www.postimees.ee/' }],
  ['ava facebook', { kind: 'goTo', url: 'https://www.facebook.com/' }],
  ['ava google', { kind: 'goTo', url: 'https://www.google.com/' }],
  ['ava youtube', { kind: 'goTo', url: 'https://www.youtube.com/' }],
  ['mine delfi', { kind: 'goTo', url: 'https://www.delfi.ee/' }],
  // Round 3 (23.2): the names as an Estonian ear spells them, and what sounds like them.
  ['ava juutuub', { kind: 'goTo', url: 'https://www.youtube.com/' }],
  ['ava juutuba', { kind: 'goTo', url: 'https://www.youtube.com/' }],
  ['mine juutuubi', { kind: 'goTo', url: 'https://www.youtube.com/' }],
  ['ava jutuub', { kind: 'goTo', url: 'https://www.youtube.com/' }],
  ['ava uutuub', { kind: 'goTo', url: 'https://www.youtube.com/' }],
  ['ava jutuup', { kind: 'goTo', url: 'https://www.youtube.com/' }],
  ['mine juutuubisse', { kind: 'goTo', url: 'https://www.youtube.com/' }],
  ['ava gugel', { kind: 'goTo', url: 'https://www.google.com/' }],
  ['ava guugel', { kind: 'goTo', url: 'https://www.google.com/' }],
  ['mine guuglisse', { kind: 'goTo', url: 'https://www.google.com/' }],
  ['ava gmeil', { kind: 'goTo', url: 'https://mail.google.com/' }],
  ['ava fäisbuk', { kind: 'goTo', url: 'https://www.facebook.com/' }],
  ['ava feisbuk', { kind: 'goTo', url: 'https://www.facebook.com/' }],
  ['ava feisbuki', { kind: 'goTo', url: 'https://www.facebook.com/' }],
  ['ava mesendžer', { kind: 'goTo', url: 'https://www.messenger.com/' }],
  ['ava messendžer', { kind: 'goTo', url: 'https://www.messenger.com/' }],
  ['ava postimehes', { kind: 'goTo', url: 'https://www.postimees.ee/' }],
  ['mine delfis', { kind: 'goTo', url: 'https://www.delfi.ee/' }],
  ['ava vatsapp', { kind: 'goTo', url: 'https://web.whatsapp.com/' }],
  ['ava vatsäp', { kind: 'goTo', url: 'https://web.whatsapp.com/' }],
  ['mine vatsapi', { kind: 'goTo', url: 'https://web.whatsapp.com/' }],
  ['ava whatsap', { kind: 'goTo', url: 'https://web.whatsapp.com/' }],
  ['ava err', { kind: 'goTo', url: 'https://www.err.ee/' }],
  ['ava linkedin', { kind: 'goTo', url: 'https://www.linkedin.com/' }],
  ['ava cv.ee', { kind: 'goTo', url: 'https://www.cv.ee/' }],
  ['ava cv punkt ee', { kind: 'goTo', url: 'https://www.cv.ee/' }],
  ['ava cvkeskus', { kind: 'goTo', url: 'https://www.cvkeskus.ee/' }],
  ['ava cv keskus', { kind: 'goTo', url: 'https://www.cvkeskus.ee/' }],
  ['ava töötukassa', { kind: 'goTo', url: 'https://www.tootukassa.ee/' }],
  ['open messenger', { kind: 'goTo', url: 'https://www.messenger.com/' }],
  ['go to gmail', { kind: 'goTo', url: 'https://mail.google.com/' }],
  // Bare addresses
  ['ava ekool.ee', { kind: 'goTo', url: 'https://ekool.ee' }],
  ['go to wikipedia.org', { kind: 'goTo', url: 'https://wikipedia.org' }],
  ['mine lehele www.riigiteataja.ee', { kind: 'goTo', url: 'https://www.riigiteataja.ee' }],
  // Search (M7: the site's own search; Google and YouTube by name)
  ['otsi ilm tallinnas', { kind: 'siteSearch', query: 'ilm tallinnas' }],
  ['search for bus times', { kind: 'siteSearch', query: 'bus times' }],
  ['otsi googlest ilm tallinnas', { kind: 'goTo', url: 'https://www.google.com/search?q=ilm%20tallinnas' }],
  ['guugelda ilm', { kind: 'goTo', url: 'https://www.google.com/search?q=ilm' }],
  ['google bus times', { kind: 'goTo', url: 'https://www.google.com/search?q=bus%20times' }],
  ["otsi youtube'ist kassid", { kind: 'goTo', url: 'https://www.youtube.com/results?search_query=kassid' }],
  ['search youtube for cats', { kind: 'goTo', url: 'https://www.youtube.com/results?search_query=cats' }],
  // M7 phrases
  ['uus leht', { kind: 'newTab' }],
  ['Ava uus aken.', { kind: 'newTab' }],
  ['new window', { kind: 'newTab' }],
  ['sulge', { kind: 'closeTab' }],
  ['close', { kind: 'closeTab' }],
  ['peida riba', { kind: 'bar', show: false }],
  ['show the bar', { kind: 'bar', show: true }],
  ['kirjuta siia', { kind: 'arm', on: true }],
  ['ära kirjuta siia', { kind: 'arm', on: false }],
  ['tühjenda otsing', { kind: 'clearField' }],
  ['clear the field', { kind: 'clearField' }],
  ['pane kinni', { kind: 'pressKey', key: 'Escape' }],
  ['Enter.', { kind: 'pressKey', key: 'Enter' }],
  ['paus', { kind: 'media', action: 'pause' }],
  ['heli valjemaks', { kind: 'media', action: 'volumeUp' }],
  ['keri tagasi', { kind: 'media', action: 'back' }],
  ['täisekraan', { kind: 'media', action: 'fullscreen' }],
  // Round 5: the page's size.
  ['suurenda', { kind: 'zoom', direction: 'in' }],
  ['Suurenda lehte.', { kind: 'zoom', direction: 'in' }],
  ['suumi sisse', { kind: 'zoom', direction: 'in' }],
  ['tee suuremaks', { kind: 'zoom', direction: 'in' }],
  ['suurem tekst', { kind: 'zoom', direction: 'in' }],
  ['tee tekst suuremaks', { kind: 'zoom', direction: 'in' }],
  ['zoom in', { kind: 'zoom', direction: 'in' }],
  ['make it bigger', { kind: 'zoom', direction: 'in' }],
  ['larger text', { kind: 'zoom', direction: 'in' }],
  ['vähenda', { kind: 'zoom', direction: 'out' }],
  ['suumi välja', { kind: 'zoom', direction: 'out' }],
  ['Tee väiksemaks.', { kind: 'zoom', direction: 'out' }],
  ['väiksem kiri', { kind: 'zoom', direction: 'out' }],
  ['zoom out', { kind: 'zoom', direction: 'out' }],
  ['make it smaller', { kind: 'zoom', direction: 'out' }],
  ['tavaline suurus', { kind: 'zoom', direction: 'reset' }],
  ['algne suurus', { kind: 'zoom', direction: 'reset' }],
  ['suumi tagasi', { kind: 'zoom', direction: 'reset' }],
  ['reset zoom', { kind: 'zoom', direction: 'reset' }],
  ['normal size', { kind: 'zoom', direction: 'reset' }],
  // History
  ['mine tagasi', { kind: 'history', direction: 'back' }],
  ['Tagasi.', { kind: 'history', direction: 'back' }],
  ['eelmine leht', { kind: 'history', direction: 'back' }],
  ['edasi', { kind: 'history', direction: 'forward' }],
  ['mine edasi', { kind: 'history', direction: 'forward' }],
  ['page back', { kind: 'history', direction: 'back' }],
  ['go back a page', { kind: 'history', direction: 'back' }],
  ['go forward', { kind: 'history', direction: 'forward' }],
  // Reload
  ['laadi uuesti', { kind: 'reload' }],
  ['värskenda', { kind: 'reload' }],
  ['reload', { kind: 'reload' }],
  ['refresh the page', { kind: 'reload' }],
  // Scroll
  ['keri alla', { kind: 'scroll', direction: 'down' }],
  ['keri üles', { kind: 'scroll', direction: 'up' }],
  ['lehe algusesse', { kind: 'scroll', direction: 'top' }],
  ['lehe lõppu', { kind: 'scroll', direction: 'bottom' }],
  ['scroll down', { kind: 'scroll', direction: 'down' }],
  ['scroll to the top', { kind: 'scroll', direction: 'top' }],
  // Round 3 (23.2): a little, slowly, stop.
  ['keri natuke alla', { kind: 'scroll', direction: 'down', mode: 'little' }],
  ['Natuke alla.', { kind: 'scroll', direction: 'down', mode: 'little' }],
  ['keri natuke üles', { kind: 'scroll', direction: 'up', mode: 'little' }],
  ['natuke üles', { kind: 'scroll', direction: 'up', mode: 'little' }],
  ['scroll down a little', { kind: 'scroll', direction: 'down', mode: 'little' }],
  ['keri aeglaselt alla', { kind: 'scroll', direction: 'down', mode: 'slow' }],
  ['keri tasa alla', { kind: 'scroll', direction: 'down', mode: 'slow' }],
  ['keri aeglaselt üles', { kind: 'scroll', direction: 'up', mode: 'slow' }],
  ['scroll slowly down', { kind: 'scroll', direction: 'down', mode: 'slow' }],
  ['scroll slowly up', { kind: 'scroll', direction: 'up', mode: 'slow' }],
  ['stopp', { kind: 'scroll', direction: 'down', mode: 'stop' }],
  ['Stopp.', { kind: 'scroll', direction: 'down', mode: 'stop' }],
  ['seis', { kind: 'scroll', direction: 'down', mode: 'stop' }],
  ['aitab', { kind: 'scroll', direction: 'down', mode: 'stop' }],
  ['lõpeta', { kind: 'scroll', direction: 'down', mode: 'stop' }],
  ['stop', { kind: 'scroll', direction: 'down', mode: 'stop' }],
  ['stop scrolling', { kind: 'scroll', direction: 'down', mode: 'stop' }],
  ['keri edasi', { kind: 'media', action: 'forward' }],
  // Numbers
  ['näita numbreid', { kind: 'showHints' }],
  ['show numbers', { kind: 'showHints' }],
  ['peida numbrid', { kind: 'hideHints' }],
  ['hide numbers', { kind: 'hideHints' }],
  ['vajuta viis', { kind: 'clickHint', number: 5 }],
  ['Vajuta 12.', { kind: 'clickHint', number: 12 }],
  ['klõpsa kaks', { kind: 'clickHint', number: 2 }],
  ['click five', { kind: 'clickHint', number: 5 }],
  ['press 7', { kind: 'clickHint', number: 7 }],
  // Round 3: editing inside the box (the word-bound forms are patterns in inpage.ts).
  ['mine algusesse', { kind: 'caret', to: 'start' }],
  ['Teksti lõppu.', { kind: 'caret', to: 'end' }],
  ['rea algusesse', { kind: 'caret', to: 'lineStart' }],
  ['lause lõppu', { kind: 'caret', to: 'sentenceEnd' }],
  ['sõna tagasi', { kind: 'caret', to: 'wordBack' }],
  ['go to the end', { kind: 'caret', to: 'end' }],
  ['vali kõik', { kind: 'select', what: 'all' }],
  ['vali viimane lause', { kind: 'select', what: 'lastSentence' }],
  ['select the word', { kind: 'select', what: 'word' }],
  ['kustuta täht', { kind: 'pressKey', key: 'Backspace' }],
  ['kustuta ees', { kind: 'pressKey', key: 'Delete' }],
  ['vasakule', { kind: 'pressKey', key: 'ArrowLeft' }],
  ['üks rida alla', { kind: 'pressKey', key: 'ArrowDown' }],
  ['tee uuesti', { kind: 'pressKey', key: 'Redo' }],
  ['järgmine väli', { kind: 'pressKey', key: 'Tab' }],
  ['next field', { kind: 'pressKey', key: 'Tab' }],
]

describe('browserIntent: the phrase table', () => {
  it.each(ROWS)('%s', (text, command) => {
    expect(browserIntent(text)).toEqual(command)
  })
})

describe('browserIntent: what is not a browser command', () => {
  it.each([
    // Unknown site names go on to the interpreter.
    'ava eelarve',
    'mine kokkuvõtte juurde',
    'ava kass',
    'mine koju',
    'ava aken',
    'ava mari',
    'open the budget section',
    // The document's own words.
    'järgmine',
    'eelmine',
    'go back',
    'next',
    'top',
    // Sentences that only start like a command.
    'ava messenger ja kirjuta Marile',
    'vajuta',
    'otsi',
    'google',
    'search',
    'vaheleht',
    'scroll',
    '',
    // Round 3: the word-bound editing forms live in inpage.ts, where the box text is known.
    'mine sõna homme ette',
    'vali homme',
    'kustuta kolm tähte',
  ])('%s', (text) => {
    expect(browserIntent(text)).toBeNull()
  })
})
